CREATE TABLE AUTHORS(ID BIGINT NOT NULL AUTO_INCREMENT, NAME VARCHAR(70), PRIMARY KEY (NAME));
CREATE TABLE GENRES(ID BIGINT NOT NULL AUTO_INCREMENT, TITLE VARCHAR(20), PRIMARY KEY (TITLE));
CREATE TABLE BOOKS(ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY, TITLE VARCHAR(100), AUTHOR VARCHAR(70) REFERENCES AUTHORS(NAME) , GENRE VARCHAR(20) REFERENCES GENRES(TITLE));